// 增加
export const INCREATEMENT_COUNTER = "INCREATEMENT_COUNTER";
// 减少
export const DESCMENT_COUNTER = "DESCMENT_COUNTER";

// saga
export const INCREMENTASYNC_SAGAACTION = "INCREMENTASYNC_SAGAACTION"